'use client'

import AppHeader from '@/components/AppHeader'
import './globals.css'
import { Inter } from 'next/font/google'
import FinanceContextProvider from '@/store/finance-context'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FinanceContextProvider>
          <AppHeader />
          {children}
        </FinanceContextProvider>
      </body>
    </html>
  )
}
