'use client'

import AppHeader from '@/components/AppHeader'
import './globals.css'
import { Inter } from 'next/font/google'
import FinanceContextProvider from '@/store/finance-context'
import AuthContextProvider from '@/store/auth-context'
  import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <FinanceContextProvider>
            <ToastContainer/>
            <AppHeader />
            {children}
          </FinanceContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  )
}
